version: '3.9'
services:
    vaultwarden-backup:
        image: bhannigan/vaultwarden-manage
        container_name: vaultwarden-manage
        hostname: vaultwarden-manage
        network_mode: host
        restart: on-failure:3
        stdin_open: true
        tty: true
        build: ./build

#        volumes:
#            - type: volume
#              source: data
#              target: /data
#            - type: bind
#              source: /volume1/backup/vaultwarden
#              target: /backup
              
        logging:
            driver: syslog
            options:
                syslog-address: 'udp://syslog.hannigan.ca:514'
                tag: '{{.Name}}'

volumes:
    data:
        external:
            name: vaultwarden_data
  
