#!/bin/bash
#

# determine what to do
  OPERATION=$1 
  shift
  
  TIMESTAMP=$(date '+%Y%m%d%H%M')  
  
  if [ -z "${CONTAINER}" ]; then
    echo "env variable CONTAINER not declared"
    exit 1
  fi
  
# check directories exists
  SRC=/src
  DST=/dst
  
  if [ ! -d ${SRC} ]; then
    echo input directory \'${SRC}\' does not exist
    exit 1
  fi
  if [ ! -d ${DST} ]; then
    echo output directory \'${DST}\' does not exist
    exit 1
  fi

## -- vaultwarden backup --
##

function vw-backup () 
{
  BACKUP_FILE=${DST}/${CONTAINER}-${TIMESTAMP}.tgz
  
  cd ${SRC}
  
  # backup the sqlite3 database
  sqlite3 db.sqlite3 "VACUUM INTO './db-${TIMESTAMP}.sqlite3'"

  ATTACHMENTS=""

  if [ -d "attachments" ]; then
    ATTACHMENTS="attachments"
  fi

  # copy database backup and attachments folder into tarball
  tar cfz ${BACKUP_FILE} ${ATTACHMENTS}  db-${TIMESTAMP}.sqlite3

  if [ ! -f ${BACKUP_FILE} ]; then
    echo failed to create backup file \'${BACKUP_FILE}\'
  fi

  # remove backup copy of database
  rm db-${TIMESTAMP}.sqlite3

  exit 0
}


## -- vaultwarden restore --
##

function vw-restore () 
{
  echo restore not implemented
  exit 0
}


## -- vaultwarden export --
##

function vw-export () 
{
  echo export not implemented
  exit 0

  EXPORT_FILE=${DST}/${CONTAINER}-${TIMESTAMP}.txt

  cd ${SRC}
  
  # backup the sqlite3 database
  sqlite3 db.sqlite3 "EXPORT INTO '${EXPORT_FILE}'"

  if [ ! -f ${EXPORT_FILE} ]; then
    echo failed to create export file \'${EXPORT_FILE}\'
  fi

  exit 0
}


## -- main --
##

case ${OPERATION} in
  backup)
    vw-backup $*
    ;;

  restore)
    vw-restore $*
    ;;

  export)
    vw-export $*
    ;;

  *)
    echo unknown operation \'${OPERATION}\'
    exit 1
    ;;
  esac
